# Generated by Django 6.0.4 on 2026-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=750)),
                ('category', models.CharField(max_length=255)),
                ('billing_model', models.CharField(max_length=255)),
            ],
        ),
    ]
