# Generated by Django 6.0.4 on 2026-04-23 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_category_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='service/'),
        ),
    ]
