# Generated by Django 6.0.4 on 2026-05-02 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceinventary'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='value_generated',
            field=models.TextField(blank=True, max_length=750, null=True),
        ),
    ]
