# Generated by Django 6.0.4 on 2026-05-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_value_generated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceinventary',
            old_name='Services_value',
            new_name='services_value',
        ),
    ]
